### ISSUE TITLE
Fade to Values

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-module-generic-sacn#2]
Great Module however I have found the following issues when using the Fade to Values Action it works fine if Starting Channel is set to either 1 or 2 but when starting channel is over 2 I get no change to any of the channel values.

**Comment by wde** [comment]
I have the same issue. Is it possible that this module is no longer supported?

**Comment by zmcandee** [comment]
I know longer have a setup for testing or much time for development so this is more or less abandoned for the moment.  I would also strongly recommend against using fade. It is pretty cpu and network intensive sending packets for every step in the fade.

If anybody wants to jump in and try fixing it they can.

**Comment by wde** [comment]
Hi Zach, Thanks for letting me know. I’ll put some feelers out and thanks for your efforts.

 

I know longer have a setup for testing or much time for development so this is more or less abandoned for the moment. I would also strongly recommend against using fade. It is pretty cpu and network intensive sending packets for every step in the fade.

If anybody wants to jump in and try fixing it they can.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Julusian** [comment]
This is fixed in the 3.0 betas, and will be in 2.4.2 if that gets released
